{% set name = "datasette-graphql" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datasette-graphql-{{ version }}.tar.gz
  sha256: 1b171a7c72c316278c974ea3a1c7836cb559421599f54304ca27ef8349f9b963

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - datasette >=0.58.1
    - graphene >=3.1.0,<4.0
    - graphql-core >=3.1.7
    - python >=3.6
    - sqlite-utils

test:
  imports:
    - datasette_graphql
  requires:
    - pip

about:
  home: https://github.com/simonw/datasette-graphql
  summary: Datasette plugin providing an automatic GraphQL API for your SQLite databases
  license: SGI-B-2.0
  license_file:
    - LICENSES.md

extra:
  recipe-maintainers:
    - andersy005
